#pragma once
#include <SDL.h>
#include "TGL_String.h"
#include "TGL_List.h"
#include "TGL_Util.h"
#include "TGL_Rgb.h"
#include "TGL_Color.h"
#include "TGL_Window.h"
#include "TGL_Image.h"
#include "TGL_Point.h"
#include "TGL_Rect.h"
#include "TGL_Size.h"
